### ISSUE TITLE
Could the version also updated in npm?

### ISSUE THREAD

**Issue by piwonesien** [jedmao/simple-glob#2]
Then the dependency warnings should disappear.

**Comment by McGiverGim** [comment]
Yes please!!!

**Comment by jednano** [comment]
I'll accept a PR.

**Comment by piwonesien** [comment]
@jedmao I think a PR is impossible ... It has to be done by the owner of the package (you): https://docs.npmjs.com/getting-started/publishing-npm-packages#how-to-update-a-package

**Comment by jednano** [comment]
Fixed in version 0.2.0, published. Thanks for the help!
